language: "node_js"

node_js:
  - 0.8

branches:
  only:
    - develop

before_install:
  - npm rebuild
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq-server restart

before_script:
  - cd src
  - nohup node start.js &
  - sleep 10
  - cd ..
  - cd test
  - node E2Etest.js
  - cd ..

notifications:
   email:
      - gll@tid.es
