language: "node_js"

node_js:
  - 0.8
  
services:
  - rabbitmq # will start rabbitmq-server
  - mongodb # will start mongodb

branches:
  only:
    - develop

before_install:
  - npm rebuild
  - sudo rabbitmq-plugins enable amqp_client
  - sudo service rabbitmq-server restart
  - sleep 5

before_script:
  - cd src
  - node start.js &
  - sleep 10
  - cd ../test
  - node E2Etest.js

notifications:
   email:
      - gll@tid.es

