language: "node_js"

node_js:
  - 0.8

branches:
  only:
    - develop

before_install:
  - rm -rf node_modules
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - sudo service rabbitmq restart

before_script:
  - cd src
  - node start.js

notifications:
   email:
      - gll@tid.es
