language: "node_js"

node_js:
  - 0.8

branches:
  only:
    - develop

before_install:
  - npm rebuild

before_script:
  - rabbitmq-plugins list
  - cd src
  - node start.js &
  - sleep 10
  - cd ../test
  - node E2Etest.js

notifications:
   email:
      - gll@tid.es

