language: "node_js"

node_js:
  - 0.8

branches:
  only:
    - develop

before_install:
  - rm -rf node_modules
  - sudo rabbitmq-plugins enable rabbitmq_stomp

notifications:
   email:
      - frsela@tid.es
      - gll@tid.es
